d1 = {"domain": ["EMERALD"], "serviceabilityCheckEnabled": ["true"],
      "filters": ["sid \"448b0802 db83 2181 d3a3 a6e0dd675064\""],
      "gclid": ["eaiaiqobchmitn nv_pw4qivldurch0elaegeaayasaaeglvivd_bwe"], "qid": ["1556428675"],
      "buyabilityRankingEnabled": ["true"], "smart-classify": ["true"], "marketplace": ["flipkart"],
      "tags[]": ["kashmir-willow-bats"], "query-guide": ["true"], "availabilityCheckEnabled": ["true"],
      "products-call": ["true"], "retry-spell-suggestion": ["true"], "affid": ["expertsnic"],
      "keywords": ["pedastal fans for home"], "signinreqd": ["1"], "mustang": ["enabled", "enabled"],
      "select": {"substores": ["off"]}, "semcmpid": ["sem_8024046704_brand_eta_goog"],
      "utm_campaign": ["affiliate0608"], "zone": ["ZONE-3"], "xServiceableMarketplaces": ["flipkart"],
      "query-stub": ["true"], "geoBrowse": ["enabled"], "xMarketplaceContext": ["flipkart"], "nova": ["enabled"],
      "redirection": ["true"], "enableNewHeaders": ["true"], "trackingId": ["intent_broadening"],
      "includeBuyability": ["true"], "bucket[]": ["Nymeria_1567", "CiImprovement"], "xDomain": ["flipkart"],
      "type": ["healthcheck"], "elv": [
        "axxfreiqqd9r3guelwapulpqfnxjj4m0upryubmtopxzgk8nqnkzzx6q5g5bamh5gdcopbwzyek!d5deve5ucawlrg9r8xbzli0m9mx9himj"],
      "sort": ["price_desc"], "groupingImpl": ["siblings"], "widgetizationABEnabled": ["true"], "th": ["1"],
      "isRelatedSearch": ["true"], "s_kwcid": ["al!739!3!265058422074!p!!g!!flipkart"],
      "sprefix": ["pedstal fa,aps,666"], "psc": ["1"], "hudsonCacheMiss": ["miss2"], "groceryContext": ["true"],
      "ranking-control": ["22Mar"],
      "eligibleBenefits": ["EAFlash,EASale,extendedReturn,freeShip,priorityCX,priorityShip,rewardStore"],
      "businessZone": ["bz_del_01"], "phone": ["8123313802"], "lzn": ["true"], "item_id": ["11533182185673200"],
      "listingCount": ["3"], "lid": ["lstartec89nsh4ypdczjxs7xy"], "marketplaceId": ["GROCERY"],
      "index-experiment": ["dd"], "src": ["od"], "viewinapp": ["1"], "display-augment": ["false"], "img": ["1"],
      "auto-correct": ["true"], "sr": ["8 19"],
      "facets": {"length[]": ["Knee Length", "Below Knee", "Maxi/Full Length"], "towel_type[]": ["Bath"],
                 "ssd_capacity[]": ["128 GB", "256 GB", "512 GB"], "hooded[]": ["Yes"],
                 "moisturizer_type[]": ["Lotion"], "bag_weight[]": ["1 kg - 1.9 kg", "0.9 kg and Below"],
                 "mechanism[]": ["Manual"], "types_of_devices_controlled[]": ["TV"],
                 "number-of-usb-ports[]": ["1", "2"], "wheels_included[]": ["Wheels Included"],
                 "availability[]": ["Exclude Out of Stock"], "paper_finish[]": ["Matte"],
                 "resolution_type[]": ["Full HD", "Full HD+", "FHD+"], "form_factor[]": ["Hair Spray", "Spray"],
                 "strap_material[]": ["Genuine Leather"], "power[]": ["501 W - 750 W"],
                 "sticker_type[]": ["Fridge Sticker"], "platform[]": ["PC", "Android"], "width[]": ["36 inch (Single)"],
                 "chuck_size[]": ["18 mm"], "device[]": ["Laptop"], "reading_power[]": ["+ 1.50"],
                 "reversible[]": ["Reversible"], "skin_tone[]": ["Wheatish"], "dial_shape[]": ["Round"],
                 "spherical_power[]": ["-2.75"], "skill_set[]": ["Motor Skills"],
                 "combo_type[]": ["Bracelet", "Candle Tealight Holder", "Chocolates", "Cushion",
                                  "Cushion, Greeting Card, Rakhi", "Cushion, Soft Toy, Rakhi", "Cushion Cover",
                                  "Goggle", "Greeting Card, Rakhi", "Lumba", "Mug", "Mug, Greeting Card, Rakhi",
                                  "Mug, Key Ring, Greeting Card, Chawal Roli Pack",
                                  "Mug, Key Ring, Greeting Card, Rakhi", "Rakhi, Greeting Card",
                                  "Rakhi, Greeting Card, Cushion", "Rakhi, Greeting Card, Mug",
                                  "Rakhi, Greeting Card, Mug, Key Ring", "Rakhi, Mug, Key Ring", "Rakhi, Thali",
                                  "Showpiece", "Sippers", "Table Clock", "Table Clock, Rakhi", "Thali", "Thali, Rakhi"],
                 "sunscreen_type[]": ["Gel"], "ideal_for%5B%5D": ["Girls", "Boys", "Boys+%26+Girls"],
                 "display_size[]": ["8 Inch"], "occasion[]": ["Festive/Wedding"],
                 "pet_type[]": ["Fish & Aquatics", "Reptiles"], "set_contents[]": ["Home Gym Station"],
                 "fragrance[]": ["Aroma"], "shipping_speed[]": ["Faster Delivery"], "game_modes[]": ["Single-Player"],
                 "upholstery_included[]": ["Upholstery Included"], "frame_shape[]": ["Round", "Aviator"],
                 "thermoware[]": ["Yes"], "sleev[]": ["3/4 Sleeve"], "type[]": ["Running Shoes"],
                 "number_of_cups[]": ["6"], "processor_name[]": ["AMD", "Intel"], "number_of_usb_ports[]": ["Two"],
                 "frequency_band[]": ["Dual Band"], "printer_output[]": ["Color"], "suitable_for[]": ["Moto C Plus"],
                 "interface[]": ["Wireless"], "ring_type[]": ["ring"], "illuminated_keys[]": ["Illuminated Keys"],
                 "touch_screen[]": ["Yes"], "foldable[]": ["Foldable"], "wiring[]": ["Wirefree"],
                 "charger_present[]": ["Yes"], "phase[]": ["Single-phase"], "headset_type[]": ["In the Ear"],
                 "front_brake[]": ["Wire Brake"], "maximum_power_output[]": ["2001 - 4000 W"], "pack_type[]": ["Pen"],
                 "power_consumption_(w)_[]": ["65 W"], "display[]": ["Full HD"],
                 "ideal_for_family_size[]": ["Family of 4"], "number_of_counts[]": ["6000"],
                 "benefit[]": ["Water Proof"], "configuration[]": ["Stereo"], "seam_type[]": ["Seamed"],
                 "discount_range_v1%5B%5D": ["50%2 me d.//twmwy/jh//hg/g/x/v/b//.zfx/5+or+More"],
                 "enclosure_type[]": ["Sealed Enclosure"],
                 "fragrance_classification[]": ["Extrait De Parfum", "Perfume", "Eau de Parfum"],
                 "disposability[]": ["Daily"], "jra,ixy,jgq[]": ["true"], "socket_type[]": ["LGA1151"],
                 "filter_type[]": ["Activated Carbon"], "dedicated_graphics_memory[]": ["2 GB"],
                 "graphic_processor_name[]": ["NVIDIA Geforce RTX"], "brand[]": ["Plum"],
                 "hair_condition[]": ["Damaged Hair"], "sander_type[]": ["Disc Sander"],
                 "screen_size[]": ["12 inch - 12.9 inch"],
                 "compatible_laptop_size[]": ["14 inch", "14 inch inch", "14 inch Inches"],
                 "compartments[]": ["4", "5", "6", "7", "8", "10"], "voice_calling_facility[]": ["Yes"],
                 "cable_length[]": ["1 - 1.5 m"], "height[]": ["21 to 30 cm"], "jug_type[]": ["Water"],
                 "energy_rating[]": ["4 Star"], "weight_range[]": ["20 - 40 kg"],
                 "seating_capacity[]": ["1 Seater", "2 Seater", "3 Seater"],
                 "exams[]": ["Civil Services Prelims & Mains", "Civil Services General"],
                 "connectors_type[]": ["Type-C"], "number_of_hdmi_ports[]": ["One"], "sport_type[]": ["Multipurpose"],
                 "panel_view[]": ["Single Panel"], "maximum_magnification[]": ["20 x"], "wall_mountable[]": ["No"],
                 "spray[]": ["Yes"], "capacity[]": ["6.1 - 7 kg"],
                 "windshield_wiper_type[]": ["Passenger And Driver Side Wipers"], "pack_of[]": ["2"],
                 "bulb_included[]": ["Yes"], "material[]": ["Sterling Silver"], "electric[]": ["Yes"],
                 "compatible_baby_weight[]": ["7 - 12 Kgs"], "number_of_cores[]": ["Octa Core"],
                 "head_support[]": ["Head Support"], "mirror_surface[]": ["Non Planar"], "organic[]": ["Organic"],
                 "bulb_used[]": ["CFL"], "number_of_tools[]": ["13"], "mirror_placement[]": ["Exterior"],
                 "purification_technology[]": ["RO + UV"], "type_of_clock[]": ["Standard", "Station Clock"],
                 "data_rate[]": ["DDR4"], "maximum_aperture[]": ["F 1.0 - F 2.8"], "ductless[]": ["Yes"],
                 "wired/wireless[]": ["Wireless"], "thickness[]": ["5.0 mm - 7.9 mm"], "number_of_steps[]": ["7"],
                 "filling_material[]": ["Memory Foam", "Gel"], "genre[]": ["Documentary"], "container_type[]": ["Tin"],
                 "suitable_location[]": ["Indoor"], "number_of_poles[]": ["4"], "memory_size[]": ["4 GB"],
                 "strung_type[]": ["Unstrung"], "rim_diameter[]": ["15"], "choli_fabric[]": ["Cotton"],
                 "chipset_manufacturer[]": ["NVIDIA"], "face_shape[]": ["Oval", "Round"],
                 "table_shape[]": ["Rectangle"], "age_classification[]": ["1 - 3 Years(Toddler)"],
                 "vase_included[]": ["Yes"], "mega_pixel[]": ["18 to 23.99 MP"], "rise[]": ["Low Rise"],
                 "formulation[]": ["Crayon/Stick"], "value_packs[]": ["Pack of 4", "Pack of 3"], "star[]": ["5 Star"],
                 "microphone_present[]": ["Yes"], "size_in_number[]": ["36"], "rod_power[]": ["Medium Heavy"],
                 "latest_arrivals[]": ["Last 150 Days"], "occassion[]": ["Evening/Party"],
                 "willow_type[]": ["Poplar Willow"], "number_of_pc[]": ["1 - 50"], "rating[]": ["4\u2605 & above"],
                 "fit[]": ["Slim"], "network_type[]": ["4G", "4G VOLTE"],
                 "khjhkj[]": ["Over the Knee", "Calf Length", "Thigh", "Knee High"], "ink_color[]": ["Black"],
                 "diary_type[]": ["Notebook"], "wheels[]": ["Spinner (4 Wheels)"], "brightness[]": ["3001 lm & Above"],
                 "mechanism_type[]": ["Pull Out"], "reverse_rotation[]": ["Reverse Rotation"],
                 "numberof_slices[]": ["4"], "power_output[]": ["Above 5.0 amp"], "food_type[]": ["Dry"],
                 "room_size[]": ["151 to 200 sqft"], "age[]": ["9 - 12 Years"], "chimney_size[]": ["60 - 75 cm"],
                 "fretboard_material[]": ["Rosewood"], "uk_size[]": ["4.5"], "pa_rating[]": ["PA++", "PA+++"],
                 "case_material[]": ["Plastic"], "compatible_device[]": ["4g phones", "Android & iOS"],
                 "kajal_form[]": ["Gel"], "display_type[]": ["AMOLED", "OLED"], "ignition_system[]": ["Automatic"],
                 "power_consumption[]": ["750 - 1000 W"], "blower_type[]": ["Dust Extraction Blower"],
                 "response_time[]": ["5 ms and Below"], "rechargeable[]": ["No"], "sari_style[]": ["Half & Half Sari"],
                 "lens_material[]": ["Glass"], "washing_system[]": ["Tumble"], "num_of_cells[]": ["12"],
                 "coverage_area[]": ["250 sq ft"], "transparency[]": ["Transparent"],
                 "class_classification[]": ["Secondary School (Class 5+)"], "secondary_camera[]": ["8 - 11.9 MP"],
                 "supported_interface[]": ["Bluetooth"], "customisable[]": ["Yes"], "finish[]": ["Matte"],
                 "quantity[]": ["400 g"], "graphics_memory_type[]": ["GDDR5"], "knife_type[]": ["Paring"],
                 "body_color[]": ["Blue"], "lens_type_supported[]": ["Single Vision"],
                 "popular_collections[]": ["Blue Back Cover"], "painting_theme[]": ["Botanical", "Floral"],
                 "gear[]": ["6 Gear", "24 Gear", "7 Gear", "21 Gear", "21 Speed", "27 Gear", "18 Gear"],
                 "Connectivity[]": ["VGA", "HDMI"], "alarm[]": ["Yes"], "price_range.from": ["199"],
                 "upholstery_material[]": ["Leatherette", "Half-leather", "Bonded Leather", "Leather",
                                           "Protected Leather"], "no_of_color_pencils[]": ["24 -36"],
                 "discount_range_v1[]": ["30% or More"], "promo%5B%5D": ["nb:mp:0392e61717"], "prime_zoom[]": ["Prime"],
                 "number_of_photos[]": ["1 to 3"], "fade[]": ["Light Fade", "Clean Look"],
                 "mirror_operation[]": ["Manual"], "function_type[]": ["Fully Automatic Top Load"],
                 "laptop_size[]": ["14 inch - 14.9 inch"], "number_of_hooks[]": ["7 & Above"], "aspect_ratio[]": ["70"],
                 "compatible_products[]": ["Videocon A15Plus", "Samsung Galaxy S3 Neo GT-I9300I",
                                           "Lenovo B490 (59-381836) Laptop (3rd Gen Ci3/ 2GB/ 500GB/ DOS)",
                                           "Karbonn Smart A10", "Apple 128 GB iPad with Retina Display and Wi-Fi",
                                           "Samsung Galaxy tab 750",
                                           "HP 15-r005TX Notebook (4th Gen Ci3/ 4GB/ 500GB/ Win8.1/ 2GB Graph) (G8D29PA)"],
                 "bonsai[]": ["Yes"], "storage_type[]": ["Drawer"], "weight_supported[]": ["20 kg"],
                 "height_when_open[]": ["240"], "sim_type[]": ["Dual Sim"], "system_memory[]": ["8 GB DDR4"],
                 "attachment_mechanism[]": ["Magnetic"], "hard_disk_capacity[]": ["500 GB"],
                 "durability_certification_&_warranty[]": ["Durability Certified with Warranty"],
                 "frame_included[]": ["Frame Included"], "cover_type[]": ["Full Cover"],
                 "promo[]": ["nb:mp:03c12aba24"], "curve_tv[]": ["Yes"], "compatible_os[]": ["Android & iOS"],
                 "launch_year[]": ["2019"], "vehicle_brand[]": ["Honda"], "usage_timing[]": ["Pre-workout"],
                 "armrest_included[]": ["Armrest Included"], "hdd_capacity[]": ["1 TB"],
                 "pack_of_[]": ["10 and Below", "11 - 20", "21 - 30", "31 - 40", "40 and Above"],
                 "bangle_size[]": ["2/6"], "bails_included[]": ["With Bails"], "size_group[]": ["M (7-12 kg)"],
                 "color[]": ["Blue", "Brown", "Green", "Grey", "Maroon", "Orange", "Red", "Yellow"],
                 "body_material[]": ["Copper"], "discount_range[]": ["30% - 40%", "40% - 50%", "More than 50%"],
                 "maximum_load_capacity[]": ["1000g - 2000 g", "Above 2000 g"], "control[]": ["Touch Panel"],
                 "condenser_coil[]": ["Copper"], "processor[]": ["Core i5"], "weight[]": ["1.9 KG to 2.1 KG"],
                 "interface_type[]": ["SATA III", "SATA II", "SATA"], "padding[]": ["Non Padded"],
                 "ideal_usage[]": ["Egg Container"], "card_slot[]": ["11 - 15 Slots", "6 - 10 Slots"],
                 "s erviceability[]": ["true"], "waist_rise[]": ["Low Rise"], "speed[]": ["7 Gear"],
                 "multipack_set[]": ["Above 10", "7 - 10", "3 - 6", "Less than 3"],
                 "product_type[]": ["Ginger Garlic Paste", "Tamarind Paste"], "filter_standard[]": ["1"],
                 "size_uk[]": ["7"], "lock_type[]": ["Biometric"], "number_of_recliners[]": ["5", "6", "7"],
                 "serviceability[]": ["true"], "number_of_eggs_boiled[]": ["14"],
                 "coverage[]": ["Full Coverage", "Medium Coverage"], "applied_for[]": ["Dry Lips"],
                 "soft_close[]": ["Soft Close"], "rolling_pin_type[]": ["Textured Pin"],
                 "number_of_containers[]": ["1 - 3 Containers"],
                 "theme[]": ["Detailed Ethnic", "Platforms", "Metallic Slip-on Sandals", "Wedding Look", "Metallic",
                             "Festive Wedges", "Mojris", "Ethnic Wedges", "Embroidered", "Pencil Heels", "Embellished",
                             "Embellished Ethnic"], "scented[]": ["Scented"], "price_range[]": ["Rs. 1001 - Rs. 2000"],
                 "battery_capacity[]": ["5000 mAh & Above"], "lens[]": ["Mirrored"],
                 "speciality[]": ["High Performance"], "dial_color[]": ["Black"], "wheel_diameter[]": ["110 mm"],
                 "night_vision[]": ["Night Vision"], "dietary_preference[]": ["Low Cholesterol"],
                 "convenience_features[]": ["Android Connectivity"], "processor_clock_speed[]": ["1.8 GHz & Above"],
                 "peak_power_handling[]": ["201 - 400 W"], "number_of_bars[]": ["2"],
                 "subscription_validity_(years)[]": ["3 Years"], "bluetooth_version[]": ["v2.1+EDR"],
                 "brand_flavor[]": ["Chocolate"], "transfer_speed[]": ["300 Mbps"], "benefits_(face)[]": ["Daily Care"],
                 "gear_type[]": ["Non Geared"],
                 "secondary_material[]": ["Engineered Wood", "Solid Wood, Fabric", "Solid Wood"],
                 "fulfilled_by[]": ["Flipkart Assured"], "stick_technology[]": ["Wood"], "flow_rate[]": ["Medium Flow"],
                 "lens_mount[]": ["EF", "EF-S", "Canon Mount"], "protein_type[]": ["Weight Gainers/Mass Gainers"],
                 "screen_resolution[]": ["Full HD"], "flavor[]": ["Guava", "Lychee", "Pomegranate"],
                 "benefits[]": ["Anti-acne & Pimples"], "grain_size[]": ["Long Grain"],
                 "external_material[]": ["COTTON"], "headboard_type[]": ["Upholstered"], "design[]": ["Snake"],
                 "tape_width[]": ["51 mm & Above"], "warranty[]": ["12 months"], "tree_type[]": ["Fir"],
                 "gold_purity25[]": ["22kt"], "designed_for[]": ["Door", "Long Door"],
                 "focal_length[]": ["250 mm & Above"], "lunch_box_material[]": ["Glass"],
                 "door_type[]": ["Sliding Door"], "headphone_type[]": ["Over the Ear"],
                 "grade_name[]": ["Refurbished - Very Good"], "operating_system[]": ["Android Based"],
                 "blade_material[]": ["Stainless Steel"], "graphic_memory_capacity[]": ["4 GB"],
                 "frame_material[]": ["Wooden"], "usage_type[]": ["Disposable"], "gold_purity[]": ["18kt"],
                 "headboard_included[]": ["Headboard Included"], "thread_count[]": ["120 to 159"],
                 "design_type[]": ["Tube Less"], "filter_material[]": ["Carbon"], "battery_type[]": ["Lithium Polymer"],
                 "maximum_pressure[]": ["121 Bar - 150 Bar"], "clock_speed[]": ["2 - 2.5 GHz", "1.5 - 1.9 GHz"],
                 "organic_type[]": ["Natural"], "frequency[]": ["2.4 GHz, 5 GHz"], "maximum_load[]": ["650 kg"],
                 "hair_type[]": ["All Hair Types"], "application_type[]": ["Self Adhesive"],
                 "rated_pressure[]": ["6 Bar & Above"], "glue_sticks_included[]": ["No"], "mount_type[]": ["Stand"],
                 "ram[]": ["4 GB"], "diameter[]": ["30.48 cm"], "painting_type[]": ["Digital Reprint"],
                 "number_of_sheets[]": ["500 Sheets and Above"], "sleeve[]": ["Full Sleeve"],
                 "delivery_condition[]": ["Non-assembled"], "size_-_euro[]": ["38"],
                 "wireless_speed[]": ["600 - 750 Mbps"], "layers[]": ["Multiple"],
                 "family_size[]": ["Family of 5 or more"], "sleeves[]": ["Roll-up Sleeve", "Full Sleeve"],
                 "neck[]": ["V-neck"], "temperature_type[]": ["High Temperature"], "fabric[]": ["Cotton Blend"],
                 "lid_type[]": ["Outer Lid"], "diya_type[]": ["Hanging"], "auto_clean[]": ["Yes"],
                 "graphic_processor_series[]": ["1070"], "internal_storage[]": ["32 - 63.9 GB"],
                 "life_style[]": ["Everyday Use"], "primary_camera[]": ["21 MP & Above", "16 - 20.9 MP"],
                 "graphic_memory[]": ["1 GB", "2 GB"], "headset_design[]": ["In-ear-canalphone"],
                 "brnad[]": ["Crystal Furnitech", "Furnicity", "HomeTown", "Parin", "RoyalOak", "Spacewood",
                             "The Attic", "UNICOS", "Urban Ladder", "Woodness"], "set_of[]": ["4"],
                 "spf[]": ["SPF 16 - SPF 30"], "section_width[]": ["175 mm"], "ram_type[]": ["DDR4"],
                 "lens_color[]": ["Orange"], "food_preference[]": ["Vegetarian"],
                 "trimmer_type[]": ["Corded & Cordless"],
                 "closure[]": ["Tie-up", "Drawstrings", "Zipper", "No Closure", "Knots"],
                 "solar_panel_wattage[]": ["0.4 W"], "mirror_included[]": ["Mirror Included"],
                 "number_of_doors[]": ["3", "4"],
                 "usage_[]": ["Fitness & Outdoor", "Health & Medical", "Watchphone", "Safety & Security", "Notifier"],
                 "fragrance_type[]": ["Deodorant Spray", "Deodorant Roll-on", "Body Spray", "Perfume Body Spray"],
                 "strap_color[]": ["Gold"], "tool_usage_type[]": ["Professional"], "panel_type[]": ["IPS Panel"],
                 "inbuilt_speaker[]": ["Yes"], "number_of_chairs[]": ["4"], "rivet_gun_style[]": ["Slow Hitting"],
                 "number_of_pieces_per_pack[]": ["2", "4"], "tank_capacity[]": ["10"], "size[]": ["S"],
                 "sensor_type[]": ["CMOS"], "number_of_blades[]": ["3"], "language[]": ["Hindi"],
                 "air_suction_capacity[]": [">1200"], "format[]": ["DVD"], "screen_type[]": ["LED"],
                 "age_group[]": ["12 - 13 Years", "14 - 15 Years", "13 - 14 Years", "15 - 16 Years", "12 - 14 Years"],
                 "primary_material[]": ["Fabric"], "skin_type[]": ["All Skin Type"], "vehicle_model_year[]": ["2012"],
                 "operating_system_version_name[]": ["Pie"], "regional_speciality[]": ["Maharashtra"],
                 "headphone_design[]": ["Earbud", "Ear Clip", "Canalphone", "Behind the Neck"],
                 "storage_included[]": ["Storage Included"], "defrosting_type[]": ["Frost Free"],
                 "application_area[]": ["Lips"], "collection[]": ["Ethnic"], "light_source[]": ["CCFL"],
                 "framed_frameless[]": ["Framed", "Frameless"], "brand%255b%255d": ["force+10+by+liberty", "liberty"],
                 "resolution[]": ["Ultra HD (4K)"], "usage[]": ["Driving", "Eye Protection"],
                 "number_of_drawers[]": ["4"], "processor_brand[]": ["Mediatek"],
                 "ocassion[]": ["Beach Wear", "Party", "Casual"], "straps[]": ["Regular"],
                 "features[]": ["Water Resistant"], "bulb_type[]": ["LED"], "placement_position[]": ["Side Window"],
                 "binding[]": ["Paperback"], "maximum_brightness[]": ["2500 nm - 3000 lm", "3001 lm and Above"],
                 "neck_line[]": ["Boat Neck"], "maximum_capacity[]": ["Above 300 psi"], "body_type[]": ["Soft Body"],
                 "character[]": ["Superman", "Disney Mickey", "Peppa Pig", "Black Batman", "Mickey", "SPIDERMAN",
                                 "Spider man", "marvel Avengers", "Disney Princess", "BatMan", "Disney Frozen Elsa",
                                 "micky mouse", "Micki Mouse", "Minnie Mouse", "AVENGERS", "chhota bheem", "Doraemon",
                                 "Wonder Woman", "SUPERMAN", "Chhota Bheem", "SPIDER MAN", "SpiderMan", "Mickey Minnie",
                                 "MIckey", "Caption America", "Spider Man", "Disney Mickey Mouse", "Mickey,Minnie",
                                 "Micky Mouse", "marvel heroes", "MICKY MINNIE", "MIcky", "avenger", "MINION AND MICKY",
                                 "MICKEY", "Spider-Man", "CAPTION AMERICA", "avengers", "Harry Potter", "Doramon",
                                 "Micke Mouse", "Peppa", "Micky", "mickey Mouse", "superman", "peppa pig", "Spiderman",
                                 "MICKEY MOUSE", "Avengers", "Iron man, avengers", "HarryPotter", "Iron Man", "micky",
                                 "Avenger", "spiderman", "Mickeymouse", "Avengers 6 Pcs. Kids Nation Action Figure",
                                 "mickey", "Hulk", "Mickey Mouse", "Captian America", "Avengers Justice League",
                                 "mickey mouse", "Marvel Avengers", "Avengers Iron Man", "doraemon", "Mickie Mouse",
                                 "Disney Frozen olaf", "SuperMan", "Iron man", "Batman", "Mickey mouse", "iron man",
                                 "Disney Mickey Minnie", "PeppaPig", "Peppa Pig.", "batman", "Marvel", "HULK",
                                 "Avengers Figure", "Marvel Avengers Set of Four", "spider man", "Spider",
                                 "Avengers 6 Pcs. Action Figure", ". Hulk", "IRON MAN", "PEPPA PIG.", "hulk", "BATMAN",
                                 "Avengers Infinity War 6 Pcs. Action Figure", "DORAEMON"],
                 "viewing_distance[]": ["6 Feet & above"], "functions[]": ["Print", "Copy", "Scan"],
                 "back_style[]": ["Regular"], "memory_technology[]": ["DDR4", "DDR3"],
                 "capacity_in_litres[]": ["1 L and Below"],
                 "outer_material[]": ["Polyester", "Microfiber", "Poly Cotton", "Cotton"],
                 "vehicle_model[]": ["Dzire", "PIK UP 4 WD"], "cover[]": ["With Cover"],
                 "audio/video[]": ["Audio & Video"], "shape[]": ["Ellipse", "Cut Corner", "Oval", "Round"],
                 "operating_power[]": ["61W- 80 W"], "fragrance_family[]": ["Fruity"], "ammonia_free[]": ["Yes"],
                 "rear_brake[]": ["Wire Brake"], "feed_type[]": ["Push-fed Gun"], "playing_level[]": ["Intermediate"],
                 "ideal_for[]": ["Men", "Men & Women"], "grip_size[]": ["G3 - 3.5 Inches"], "bed_size[]": ["Single"],
                 "gemstones[]": ["Emerald"], "technology[]": ["Inverter"], "budget[]": ["Rs. 15000 - Rs. 29999"],
                 "Length[]": ["Knee Length", "Long", "Mid", "Ankle Length"], "cap_type[]": ["Twist"],
                 "offer_type[]": ["Exchange Offer"], "steam_burst[]": ["No"], "rice_type[]": ["Basmati Rice"],
                 "tyre_size[]": ["700C inches", "27.5 inches", "26 inches", "24 inches"], "with_eject_pin[]": ["No"],
                 "connectivity[]": ["Bluetooth"],
                 "visual_condition[]": ["Minimally used with negligible scratches", "Unused with zero scratches"],
                 "battery_operated[]": ["Battery Operated"], "frame_color[]": ["Blue"], "price_range.to": ["Max"],
                 "antennae[]": ["External"], "coffee_type[]": ["Roast & Ground Coffee"],
                 "neck_type[]": ["Asymmetric Neck"],
                 "compatible_model[]": ["Samsung galaxy CORE PRIME/J2(2015)/J2(2017)"], "power_source[]": ["Battery"],
                 "number_of_shelves[]": ["3", "4", "5", "6", "7 & Above"],
                 "bowl_type[]": ["Fruit Bowl", "Sauce Bowl", "Pudding Bowl", "Serving Bowl", "Ice Cream Bowl",
                                 "Decorative Bowl"], "induction_bottom[]": ["Induction Bottom"],
                 "memory_capacity[]": ["64 GB"], "lehenga_fabric[]": ["Synthetic"], "suitable_surfaces[]": ["Glass"],
                 "cookware_included[]": ["Sauce Pan"], "refilling_type[]": ["Toner Cartridge"],
                 "water_resistance[]": ["Water Resistant"], "screen_form_factor[]": ["Curved"],
                 "compatible_mobiles[]": ["Samsung Galaxy J7 Max"], "bat_grade[]": ["Grade 4"], "style[]": ["Round"],
                 "number_of_plates[]": ["3 - 5 Plates"], "adjustable_height[]": ["Adjustable Height"],
                 "lens_type[]": ["Wide and Macro"], "number_of_compartments[]": ["More Than 3"],
                 "printer_type[]": ["Inkjet"], "exercise_type[]": ["Incline Pushups"], "pan_type[]": ["Grill"],
                 "display_technology[]": ["LED"], "frame_style[]": ["Designer", "Classic"],
                 "ring_size[]": ["12", "15", "20", "10"], "collar_type[]": ["Anti-tick"], "number_of_burners[]": ["4"],
                 "frame_type[]": ["Full Rim"], "lid_included[]": ["Yes"], "din_size[]": ["Single"],
                 "compatible_with[]": ["Laptop"], "orientation[]": ["Right Facing"], "form[]": ["Liquid"],
                 "lunch_box_capacity[]": ["250 ml - 500 ml"], "type_of_earring[]": ["Hoop Earring"],
                 "broadband_compatibility[]": ["Both (Ethernet and ADSL)"], "price_range%5B%5D": ["Rs.+201+-+Rs.+500"],
                 "used_for[]": ["Anti-hair Fall"], "fill_type[]": ["Unfilled"], "heel_height[]": ["Upto 1.5 inch"],
                 "distressed[]": ["Mild Distress"], "pattern[]": ["3D Printed"], "smart_tv[]": ["Yes"],
                 "category[]": ["0pm/0o7"], "seat_lock_included[]": ["Seat Lock Included"], "primary_color[]": ["Blue"],
                 "light_color[]": ["White"], "glass_type[]": ["Champagne Glass", "Cocktail Glass", "Wine Glass"]},
      "listings": {"price": ["true", "true"]}, "order_id": ["od115331821856732000"], "q": ["washing machines top load"],
      "s": ["gateway"], "client": {"tag": ["mobile-app-retail"]},
      "products": {"count": ["120"], "start": ["0"], "type": ["listing"]}, "source": ["ps_app_top"],
      "cmpid": ["product"], "h": [
        "at1wyy72bbmzmrqm35407tyoqtzi8zkrfhhygoedun8_c8jk4rsmdciihjrghjxaa5q0ewegwmin3iilq2qdoppp05ihdc_fwx6hzy2eza5rnrqrvgb1sqvtsu7lh4rqcgjm6m2wlq"],
      "marketplaceid": ["flipkart"], "unit_id": ["11533182185673200000"],
      "view": {"id": ["brand"], "param": ["laurel-dale"]}}

d2 = {"serviceabilityCheckEnabled": ["true"], "buyabilityRankingEnabled": ["true"], "smart-classify": ["true"],
      "tags[]": ["silk-kurtas-"], "availabilityCheckEnabled": ["true"], "products-call": ["true"],
      "mustang": ["enabled", "enabled"], "select": {"substores": ["off"]}, "zone": ["ZONE-5"],
      "tags%5B%5D": ["shaverstrimmersmen"], "geoBrowse": ["enabled"], "xMarketplaceContext": ["flipkart"],
      "xServiceableMarketplaces": ["flipkart"], "enableNewHeaders": ["true"], "expressDeliverySupported": ["true"],
      "includeBuyability": ["true"], "bucket[]": ["matching-control-25-04"], "xDomain": ["flipkart"],
      "groupingImpl": ["siblings"], "trackingId": ["ranking_attribute"], "groceryContext": ["true"],
      "eligibleBenefits": ["EAFlash,EASale,extendedReturn,freeShip,priorityCX,priorityShip,rewardStore"],
      "businessZone": ["bz_blr_01"], "facet-show": ["all"], "lzn": ["true"], "listingCount": ["3"],
      "marketplaceId": ["GROCERY"], "index-experiment": ["dd"], "auto-correct": ["false"],
      "facets": {"length[]": ["Hip Length"], "towel_type[]": ["Bath"], "ssd_capacity[]": ["256 GB", "128 GB", "512 GB"],
                 "hooded[]": ["Yes"], "serviceability.from": ["Min"], "mechanism[]": ["Powered"],
                 "number-of-usb-ports[]": ["4"], "wheels_included[]": ["Wheels Included"],
                 "availability[]": ["Include Out of Stock"], "resolution_type[]": ["FHD+"], "standard[]": ["9"],
                 "strap_material[]": ["Genuine Leather", "Synthetic Leather", "Synthetic"],
                 "power[]": ["501 W - 750 W"], "sticker_type[]": ["Self Adhesive Wallpaper"],
                 "sealer_length[]": ["0 mm"], "platform[]": ["PC"],
                 "width[]": ["30 inch (Single)", "35 inch (Single)", "36 inch (Single)"], "device[]": ["Laptop"],
                 "control_type[]": ["Touch Key Pad (Membrane)"], "corded/cordless[]": ["Corded & Cordless"],
                 "reversible[]": ["Reversible"], "occassion[]": ["Casual"], "dial_shape[]": ["WRIST WARTCH"],
                 "spherical_power[]": ["-2.75"], "skill_set[]": ["Motor Skills"], "sunscreen_type[]": ["Lotion"],
                 "display_size[]": ["10 Inches & Above"], "occasion[]": ["Formal", "Casual"], "pet_type[]": ["Dog"],
                 "fragrance[]": ["Fragrance"], "shipping_speed[]": ["Faster Delivery"],
                 "game_modes[]": ["Multi-Player"], "upholstery_included[]": ["Upholstery Included"],
                 "frame_shape[]": ["Rectangle"], "number_of_containers[]": ["1 - 3 Containers"],
                 "sleev[]": ["3/4 Sleeve"], "type[]": ["Beach Shorts"], "processor_name[]": ["Core i7"],
                 "number_of_usb_ports[]": ["Three", "Two"], "frequency_band[]": ["Tri Band", "Dual Band"],
                 "blade_length[]": ["50.8 cm"], "printer_output[]": ["Color"], "suitable_for[]": ["Beard & Moustache"],
                 "board[]": ["CBSE"], "interface[]": ["Bluetooth"], "ring_type[]": ["ring"],
                 "illuminated_keys[]": ["Illuminated Keys"], "touch_screen[]": ["Yes"], "foldable[]": ["Non-Foldable"],
                 "vase_included[]": ["Yes"], "wiring[]": ["Wirefree"], "phase[]": ["Single-phase"],
                 "headset_type[]": ["On-the-ear"], "inbuilt_speaker[]": ["Yes"], "size[]": ["S", "M"],
                 "display[]": ["HD"], "ideal_for_family_size[]": ["Large Families"], "benefit[]": ["Moisturizing"],
                 "configuration[]": ["Mono"], "with_mattress[]": ["With Mattress"], "seam_type[]": ["Seamless"],
                 "fragrance_classification[]": ["Perfume"], "disposability[]": ["Monthly"],
                 "socket_type[]": ["LGA 1151"], "filter_type[]": ["HEPA"],
                 "compatible_model[]": ["Infocus M530 3100 mAh",
                                        "Infocus M530 3100 mAh Li-Ion 100% New Original Battery for Infocus M530 (UP140005)",
                                        "Infocus M530 3100 mAh Li-Ion 100% New Original Battery for Infocus M530 (UP140025/UP140005)",
                                        "Infocus M530 3100 mAh Li-Ion Battery for Infocus M530 (UP140025/UP140005)",
                                        "Infocus M530 3100 mAh Lithium-Ion 100% Original Premium High Quality Mobile Battery for Infocus M530 - (UP140025/UP140005)"],
                 "no_of_paint_shades[]": ["17 - 24 Shades"], "graphic_processor_name[]": ["NVIDIA Geforce GTX"],
                 "brand[]": ["Lotus"], "hair_condition[]": ["Colored Hair"], "straps[]": ["Multiway", "Racer Back"],
                 "compartments[]": ["2"], "voice_calling_facility[]": ["Yes"],
                 "cable_length[]": ["Above 2 m", "1.5 - 2 m"],
                 "height[]": ["Extra Large - Above 60 cm", "Large - 31 to 60 cm"], "head_type[]": ["Extra soft"],
                 "jug_type[]": ["Water"], "energy_rating[]": ["5 Star"], "weight_range[]": ["0 - 20 kg"],
                 "seating_capacity[]": ["4 Seater"], "exams[]": ["Civil Services General"],
                 "connectors_type[]": ["Micro"], "steering_wheel_controls[]": ["Steering Wheel Controls"],
                 "dishwasher_safe[]": ["Yes"], "wall_mountable[]": ["No"], "spray[]": ["Yes"], "capacity[]": ["1 Ton"],
                 "compatible_laptop_size[]": ["14 inch"], "pack_of[]": ["3 - 6"], "bulb_included[]": ["Yes"],
                 "material[]": ["Plastic", "Silicon"], "compatible_baby_weight[]": ["0 - 5 Kgs"],
                 "number_of_cores[]": ["Quad Core"], "number_of_steps[]": ["4"], "number_of_hdmi_ports[]": ["Three"],
                 "board_material[]": ["Silver", "Crystal", "Marble"], "number_of_tools[]": ["1"],
                 "purification_technology[]": ["RO + UV + UF + TDS", "RO + UV + UF", "RO + UV + MTDS",
                                               "RO + UV + MP + MTDS", "RO + UV + TDS"], "serviceability.to": ["1250"],
                 "type_of_clock[]": ["Standard"], "data_rate[]": ["DDR4"], "maximum_aperture[]": ["F 2.8 - F 3.5"],
                 "ductless[]": ["No"], "wired/wireless[]": ["Wired"], "thickness[]": ["8 inch"],
                 "dietary_preference[]": ["Egg Free"], "filling_material[]": ["Cotton"], "genre[]": ["Racing"],
                 "container_type[]": ["Pouch", "Box"], "suitable_location[]": ["Indoor, Indoor"],
                 "memory_size[]": ["4 GB"], "strung_type[]": ["Strung"], "rim_diameter[]": ["13"],
                 "choli_fabric[]": ["Art Silk", "Chanderi", "Dupion Silk", "Pure Silk", "Raw Silk", "Satin"],
                 "chipset_manufacturer[]": ["NVIDIA"], "face_shape[]": ["Oval"],
                 "table_shape[]": ["Rectangle", "Round", "Square"], "age_classification[]": ["1 - 3 Years(Toddler)"],
                 "headboard_included[]": ["Headboard Included"], "mega_pixel[]": ["10 to 13.99 MP"],
                 "rise[]": ["Mid Rise"], "formulation[]": ["Liquid", "Cream"], "value_packs[]": ["Pack of 2"],
                 "star[]": ["5 Star", "4 Star"], "microphone_present[]": ["Yes"], "size_in_number[]": ["36", "36 inch"],
                 "rod_power[]": ["Medium Light"], "latest_arrivals[]": ["Last 30 Days"],
                 "keywords[]": ["Lunch Box", "Lunch Box, Tiffin, Milton", "Milton", "Tiffin"],
                 "skin_tone[]": ["Wheatish"], "willow_type[]": ["English Willow", "Kashmir Willow"],
                 "number_of_pc[]": ["1 - 50"], "rating[]": ["4\u2605 & above"], "fit[]": ["Flared"],
                 "heart_rate_sensor_attached[]": ["With Heart Rate Sensor"], "network_type[]": ["4G VOLTE"],
                 "khjhkj[]": ["Peds/Footie/No-Show"], "ink_color[]": ["Black", "Blue"], "diary_type[]": ["Diary"],
                 "wheels[]": ["Spinner (4 Wheels)"], "mechanism_type[]": ["Pull Out"],
                 "reverse_rotation[]": ["Reverse Rotation"], "power_output[]": ["Above 5.0 amp"],
                 "food_type[]": ["Dry"], "room_size[]": ["151 to 200 sqft"], "age[]": ["Teens"],
                 "chimney_size[]": ["60 - 75 cm"], "fretboard_material[]": ["Rosewood"], "uk_size[]": ["5"],
                 "color_type[]": ["Black"], "pa_rating[]": ["PA++++"], "case_material[]": ["Metal"],
                 "compatible_device[]": ["Bluetooth version 4.0 and below in smart phones, Tablets and PC s"],
                 "kajal_form[]": ["Gel", "Cream"], "display_type[]": ["OLED Retina Display"],
                 "ignition_system[]": ["Automatic"], "power_consumption[]": ["6 W - 10 W"],
                 "response_time[]": ["5 ms and Below"], "rechargeable[]": ["Yes"],
                 "sari_style[]": ["9 Yards Sari", "Regular Sari"], "night_vision[]": ["Night Vision"],
                 "washing_system[]": ["Impellar"], "stream[]": ["Civil Engineering"], "coverage_area[]": ["100 sq ft"],
                 "class_classification[]": ["Secondary School (Class 5+)"], "secondary_camera[]": ["21 MP & Above"],
                 "supported_interface[]": ["Cable"], "customisable[]": ["Yes"], "finish[]": ["Matte"],
                 "quantity[]": ["1 L", "1.0 L", "1.2 L", "1.5 L"], "graphics_memory_type[]": ["GDDR5"],
                 "maximum_iso[]": ["51200"], "knife_type[]": ["Chefs"], "body_color[]": ["Silver"],
                 "lens_type_supported[]": ["Bifocal and Single Vision"],
                 "popular_collections[]": ["Red Back Cover", "Multicolor Back Cover", "Blue Back Cover",
                                           "Black Back Cover"], "hdd_capacity[]": ["1 TB"],
                 "spf_rating[]": ["50", "50+"], "wall_mount[]": ["Wall Mount"], "Connectivity[]": ["HDMI"],
                 "cylindrical_power[]": ["-2"], "upholstery_material[]": ["Vinyl"],
                 "discount_range_v1[]": ["50% or More"], "prime_zoom[]": ["Zoom"], "number_of_photos[]": ["1 to 3"],
                 "fade[]": ["Clean Look"], "function_type[]": ["Fully Automatic Front Load"],
                 "laptop_size[]": ["14 inch - 14.9 inch"], "aspect_ratio[]": ["16:9"],
                 "compatible_products[]": ["XOLO Q1100", "BlackBerry Curve 9220", "Huawei Ascend Y210D",
                                           "Champion WTAB702", "Champion Wtab 7.4 / 704",
                                           "Google Nexus 7C - 1B013A 2012 Tablet"], "bonsai[]": ["No"],
                 "storage_type[]": ["HDD"], "weight_supported[]": ["10 kg"], "sim_type[]": ["Dual Sim"],
                 "system_memory[]": ["8 GB"], "attachment_mechanism[]": ["Magnetic"], "hard_disk_capacity[]": ["1 TB"],
                 "durability_certification_&_warranty[]": ["Durability Certified with Warranty"],
                 "frame_included[]": ["Frame Included"], "cover_type[]": ["Cover Not Available"],
                 "promo[]": ["nb:mp:03c9169f23"], "curve_tv[]": ["Yes"], "compatible_os[]": ["Android & iOS"],
                 "resolution[]": ["Ultra HD (4K)"], "vehicle_brand[]": ["Maruti Suzuki"],
                 "usage_timing[]": ["Pre-workout"], "armrest_included[]": ["Armrest Included"],
                 "bangle_size[]": ["2.8"], "bails_included[]": ["With Bails"], "size_group[]": ["New Born (0-5 kg )"],
                 "and[]": ["Rs.100 - Rs.500"], "body_material[]": ["Glass"],
                 "gear[]": ["18 Gear", "21 Gear", "21 Speed", "24 Gear", "27 Gear", "6 Gear", "7 Gear"],
                 "maximum_load_capacity[]": ["1000g - 2000 g", "Above 2000 g"], "control[]": ["Touch Panel"],
                 "condenser_coil[]": ["Copper"], "processor[]": ["Core i5"], "weight[]": ["10 g"],
                 "interface_type[]": ["SATA III"], "padding[]": ["Lightly Padded", "Heavily Padded"],
                 "wall_mount_support[]": ["Wall Mount Support"], "ideal_usage[]": ["AC Room"],
                 "price_range.from": ["Min"], "card_slot[]": ["11 - 15 Slots"],
                 "waist_rise[]": ["Mid Rise", "High Rise", "medium rise"], "speed[]": ["27 Gear", "24 Gear", "21 Gear"],
                 "multipack_set[]": ["3 - 6"], "filter_standard[]": ["1"], "size_uk[]": ["11", "12", "11.5", "12.5"],
                 "number_of_sticks_per_box[]": ["200"], "serviceability[]": ["true"], "coverage[]": ["Half Coverage"],
                 "cleaning_type[]": ["Wet and Dry"], "thermoware[]": ["Yes"], "theme[]": ["Laptop"],
                 "price_range[]": ["Rs. 99 and Below"], "battery_capacity[]": ["5000 mAh & Above"],
                 "supported_audio_formats[]": ["MP3", "USB", "WAV", "WMA"], "lens[]": ["UV Protection"],
                 "speciality[]": ["High Performance"], "bulb_used[]": ["CFC"], "dial_color[]": ["Black"],
                 "wheel_diameter[]": ["180 mm"], "lens_material[]": ["Glass", "Polycarbonate"],
                 "convenience_features[]": ["Android Connectivity", "Touchscreen"],
                 "processor_clock_speed[]": ["1 - 1.1 GHz"], "subscription_validity_(years)[]": ["3 Years"],
                 "brand_flavor[]": ["Chocolate"], "benefits_(face)[]": ["Whitening & Fairness", "Radiance & Glow"],
                 "gear_type[]": ["Easy Fire Shifters/Thumb Shifters", "Revo Shifters"],
                 "secondary_material[]": ["Engineered Wood", "Solid Wood", "Solid Wood, Fabric"],
                 "fulfilled_by[]": ["Flipkart Assured"], "lens_mount[]": ["E-mount", "Sony Mount"],
                 "protein_type[]": ["Whey Protein"], "screen_resolution[]": ["Full HD"], "flavor[]": ["Milk"],
                 "benefits[]": ["Sun Protection"], "grain_size[]": ["Long Grain"],
                 "headboard_type[]": ["Basic", "Closed Storage", "NA", "Open & Closed Storage", "Open Storage",
                                      "Upholstered"], "warranty[]": ["12 months"], "gold_purity25[]": ["18kt"],
                 "temple_color[]": ["Multicolor", "Maroon", "Brown", "Blue"], "lid_type[]": ["Outer Lid"],
                 "lunch_box_material[]": ["Stainless Steel"], "usage_[]": ["Watchphone"],
                 "headphone_type[]": ["Over the Ear", "On the Ear"],
                 "grade_name[]": ["Brand New", "Unboxed - Like New"], "operating_system[]": ["Android"],
                 "blade_material[]": ["Stainless Steel"], "graphic_memory_capacity[]": ["2 GB"],
                 "frame_material[]": ["Stainless steel", "Metal", "Polycarbonate", "Titanium"],
                 "usage_type[]": ["Domestic"], "gold_purity[]": ["24 (9999) K", "24 (999) K", "S 999"],
                 "thread_count[]": ["200 to 399"], "design_type[]": ["Tube"], "battery_type[]": ["Lithium Polymer"],
                 "clock_speed[]": ["1 - 1.5 GHz"], "organic_type[]": ["Organic", "Natural"],
                 "frequency[]": ["2.4 GHz", "5 GHz"], "maximum_load[]": ["290 kg"],
                 "subject[]": ["Physics", "Mathematics", "Chemistry", "Biology"], "hair_type[]": ["Curly Hair"],
                 "application_type[]": ["Self Adhesive"], "glue_sticks_included[]": ["Yes"],
                 "mount_type[]": ["Sticky Pad", "Suction Cup"], "ram[]": ["4 GB"],
                 "diameter[]": ["160 cm", "200 cm", "240 cm", "260 cm"], "painting_type[]": ["Oil", "Watercolor"],
                 "sleeve[]": ["Half Sleeve"], "delivery_condition[]": ["Pre-assembled"], "size_-_euro[]": ["28"],
                 "wireless_speed[]": ["450 - 600 Mbps", "600 - 750 Mbps", "750 - 1000 Mbps", "1000 Mbps & Above"],
                 "layers[]": ["Multiple"], "family_size[]": ["Family of 5 or more"], "sleeves[]": ["Full Sleeve"],
                 "neck[]": ["Round Neck"], "temperature_type[]": ["Adjustable Temperature"],
                 "installation_type[]": ["Drilling"],
                 "fabric[]": ["Art Silk", "Cotton Silk", "Kota Silk", "Khadi Silk", "Matka Silk", "Poly Art Silk",
                              "Poly Silk", "Printed Silk", "Pure Silk", "Raw Silk", "Silk"],
                 "focal_length[]": ["28 - 55 mm"], "auto_clean[]": ["Yes"], "graphic_processor_series[]": ["1060"],
                 "internal_storage[]": ["32 - 63.9 GB"], "life_style[]": ["Everyday Use"],
                 "primary_camera[]": ["13 - 15.9 MP"], "graphic_memory[]": ["2 GB"], "headset_design[]": ["Ear Clip"],
                 "spf[]": ["SPF 16 - SPF 30"], "section_width[]": ["175 mm"], "ram_type[]": ["DDR4"],
                 "lens_color[]": ["Pink", "Black"], "food_preference[]": ["Non-vegetarian"],
                 "trimmer_type[]": ["Cordless"],
                 "closure[]": ["Hook", "Drawstrings", "Button", "Knots", "No Closure", "Tie-up", "Zipper"],
                 "wattage[]": ["10 - 20 Watts"], "mirror_included[]": ["Yes"], "frame_type[]": ["Full Rim"],
                 "reversible_mattress[]": ["Reversible Mattress"], "speed_index[]": ["H"],
                 "fragrance_type[]": ["Body Spray", "Body Mist", "Pocket Perfume", "Perfume Body Spray",
                                      "Deodorant Stick", "Deodorant Spray", "Deodorant Roll-on", "Deodorant Gel"],
                 "lamp_life[]": ["2001 hrs - 4000 hrs"], "door_type[]": ["Sliding Door"],
                 "strap_color[]": ["Black", "Blue", "Brown", "Gold", "Grey", "Multicolor"],
                 "tool_usage_type[]": ["Car", "Bike", "Electronics", "Household", "Mobile Repair"],
                 "panel_type[]": ["IPS Panel"], "front_brake[]": ["Disc Brake"], "axis_power[]": ["-4"],
                 "number_of_chairs[]": ["6"], "number_of_compartments[]": ["2"], "pack_type[]": ["Spray"],
                 "sensor_type[]": ["CMOS"], "number_of_blades[]": ["3"], "language[]": ["Tamil"],
                 "air_suction_capacity[]": [">1200"], "format[]": ["Blu-ray"], "graphic_memory_type[]": ["GDDR5"],
                 "screen_type[]": ["LED"],
                 "age_group[]": ["12 - 13 Years", "13 - 14 Years", "14 - 15 Years", "16 Years and Above"],
                 "primary_material[]": ["Engineered Wood", "Glass"], "skin_type[]": ["Sensitive Skin"],
                 "vehicle_model_year[]": ["2017"], "operating_system_version_name[]": ["Oreo"],
                 "regional_speciality[]": ["Karnataka"], "headphone_design[]": ["Behind the Neck"],
                 "storage_included[]": ["Storage Included"], "defrosting_type[]": ["Frost Free"],
                 "collection[]": ["Ethnic"], "launch_year[]": ["2019"], "usage[]": ["Driving", "Eye Protection"],
                 "processor_brand[]": ["Snapdragon"], "ocassion[]": ["Party"], "features[]": ["MS Office"],
                 "bulb_type[]": ["LED"], "binding[]": ["Boxed Set"], "maximum_brightness[]": ["3001 lm and Above"],
                 "neck_line[]": ["Halter neck", "Halter Neck", "High Neck", "Keyhole Neck"],
                 "neck_type[]": ["Asymmetric Neck", "Round", "U Neck", "Square Neck"], "body_type[]": ["Hard Body"],
                 "character[]": ["Steffi Love", "Spiderman", "None", "Ninja Hattori", "Mickey", "Kung Fu Panda",
                                 "Hello Kitty", "Avengers"], "viewing_distance[]": ["6 Feet & above"],
                 "functions[]": ["Print", "Copy", "Scan"], "light_bulb_color[]": ["Blue"],
                 "coffee_table_included[]": ["Coffee Table Included"], "back_style[]": ["Racerback"],
                 "memory_technology[]": ["DDR4"], "capacity_in_litres[]": ["1.6 L and Above", "1.1 L - 1.5 L"],
                 "vehicle_model[]": ["A-Star"], "cover[]": ["With Cover"], "audio/video[]": ["Audio"],
                 "shape[]": ["Square", "Rectangular"], "operating_power[]": ["21W- 60 W"],
                 "fragrance_family[]": ["Fresh"], "ammonia_free[]": ["Yes"], "rear_brake[]": ["Disc Brake"],
                 "playing_level[]": ["Intermediate"], "ideal_for[]": ["Men & Women"],
                 "grip_size[]": ["G3 - 3.5 Inches", "G4 -3.25 Inches"], "bed_size[]": ["Single"],
                 "gemstones[]": ["Pearl"], "technology[]": ["Dual Inverter", "Inverter"],
                 "budget[]": ["Rs. 5000 - Rs. 9999"], "pegi_rating[]": ["12", "13+"],
                 "Length[]": ["Above Knee", "Below Knee", "Knee Length"], "offer_type[]": ["No Cost EMI"],
                 "maximum_capacity[]": ["50 - 100 psi"], "steam_burst[]": ["Yes"], "rice_type[]": ["Basmati Rice"],
                 "tyre_size[]": ["700C inches", "27.5 inches", "26 inches", "24 inches"], "with_eject_pin[]": ["No"],
                 "connectivity[]": ["Wired"], "visual_condition[]": ["Unused with zero scratches"],
                 "battery_operated[]": ["Battery Operated"], "frame_color[]": ["Golden"], "price_range.to": ["500"],
                 "dedicated_graphics_memory[]": ["4 GB"], "power_source[]": ["Solar"],
                 "number_of_shelves[]": ["7 & Above"],
                 "bowl_type[]": ["Decorative Bowl", "Fruit Bowl", "Sauce Bowl", "Serving Bowl"],
                 "induction_bottom[]": ["Induction Bottom"], "memory_capacity[]": ["64 GB"],
                 "cookware_included[]": ["Fry Pan", "Kadhai", "Tawa", "Milk Pan"],
                 "refilling_type[]": ["Refillable Ink Tank"], "water_resistance[]": ["Water Resistant"],
                 "screen_form_factor[]": ["Flat"], "compatible_mobiles[]": ["Mi Redmi 3S Prime", "Mi Redmi 3S"],
                 "bat_grade[]": ["Grade 1", "Grade 1+"], "style[]": ["Rectangular", "Retro Square", "Oval"],
                 "wired_or_wireless[]": ["Wired"], "number_of_plates[]": ["6 - 9 Plates"],
                 "adjustable_height[]": ["Adjustable Height"], "lens_type[]": ["Wide and Macro"], "smart_tv[]": ["Yes"],
                 "screen_size[]": ["15 inch - 15.9 inch"], "printer_type[]": ["Inkjet"],
                 "painting_theme[]": ["Hand Painting"], "color[]": ["Black", "Dark Blue"], "pan_type[]": ["Flat"],
                 "volume[]": ["101 dB- 200 dB"],
                 "frame_style[]": ["Retro/Vintage", "Designer", "Cool/Trendy", "Classic"], "ring_size[]": ["17"],
                 "number_of_burners[]": ["4"], "number_of_doors[]": ["3"], "lid_included[]": ["Yes"],
                 "discount_range[]": ["40% - 50%"], "din_size[]": ["Double"], "compatible_with[]": ["Mobile"],
                 "orientation[]": ["Landscape"], "form[]": ["Gel"], "lunch_box_capacity[]": ["700 ml - 1000 ml"],
                 "broadband_compatibility[]": ["Both (Ethernet and ADSL)", "Ethernet (Cable Broadband)",
                                               "Access Point Mode"], "used_for[]": ["1.5 Ton AC", "1.5 Ton A.C"],
                 "fill_type[]": ["Filled"], "heel_height[]": ["1.6 - 4 inch"],
                 "distressed[]": ["High Distress", "Knee Slit"],
                 "pattern[]": ["Floral Print", "Graphic Print", "Geometric Print", "Polka Print", "Paisley",
                               "Herringbone", "Printed"], "is_available[]": ["True"],
                 "form_factor[]": ["Desktop", "Portable", "Network"],
                 "primary_color[]": ["Black", "Blue", "Brown", "Gold", "Silver", "Multicolor", "White"],
                 "light_color[]": ["Yellow"], "glass_type[]": ["Water/Juice Glass"]}, "q": ["sindur"],
      "products": {"type": ["listing"]}, "view": {"id": ["brand"], "param": ["dsp"]}}

d1['facets'] = {
    "availability[]": ["Exclude Out of Stock"],
    "platform[]": ["PC", "Android"],
    "screen_size[]": ["12 inch - 12.9 inch"],
    "compatible_laptop_size[]": ["14 inch", "14 inch inch", "14 inch Inches"],
    "price_range.from": ["199"],
    "price_range.to": ["Max"],
    "price_range[]": ["Rs. 1001 - Rs. 2000"]
}
d2['facets'] = {
    "ssd_capacity[]": ["256 GB", "128 GB", "512 GB"],
    "price_range.from": ["Min"],
    "price_range.to": ["500"],
    "price_range[]": ["Rs. 99 and Below"]

}
import json

# print d1['facets']
# print(json.dumps(d1, indent=4, sort_keys=True))

def format_d(d):
    tmp = {}
    for k, v in d.items():
        if isinstance(v, list) and len(v) == 1:
            tmp[k] = v[0]
        else:
            tmp[k] = v
    return tmp

print(json.dumps(format_d(d2), indent=4, sort_keys=True))


# print(json.dumps(d2, indent=4, sort_keys=True))

